version: '3.8'
services:
  stg:
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    image: fidsbeexpress:${TAG}
    container_name: fids-be-express
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
  prod:
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    image: fidsbeexpress:${TAG}-production
    container_name: fids-be-express
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
  dev:
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    image: fidsbeexpress:${TAG}-development
    container_name: fids-be-express
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"