version: '3.8'
services:
  stg:
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    image: skripsi_be:${TAG}
    container_name: skripsi_express
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  prod:
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    image: skripsi_be:${TAG}-production
    container_name: skripsi_express
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  dev:
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    image: skripsi_be:${TAG}-development
    container_name: skripsi_express
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"